### ISSUE TITLE
Newrelic Ignore Transaction

### ISSUE THREAD

**Issue by vrann** [magento/up-for-grabs#1]
The issue is related to the NewRelic PHP extension.

#### Problem

The data is served as JSON from the /admin/.../index/render controller. One of the columns being rendered contains HTML email body content, which is properly escaped as a string in the JSON. 

However, the New Relic PHP agent intercepts the transaction, interprets the escaped HTML as a standard page, and injects (unescaped) JS into it. This invalidates the JSON and causes the UI component to throw an error.

#### Design

New Relic module should be calling `newrelic_ignore_transaction()` before any UI components are rendered (https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_ignore_transaction)

The framework-level interface should be introduced, e.g ReportingInterface::disable and implemented in the NewRelic extension with the newrelic_ignore_transaction function call. ReportingInterface::disable should do nothing in default implementation.

Magento module should call ReportingInterface::disable and be sure that if NewRelic installed, report will not be generated.

**Comment by scottsb** [comment]
This is already handled a different way in the pending PR magento/magento2#10521. The approach suggested here is more explicit, but the other has more broad-reaching benefits.

**Comment by toddbc** [comment]
There can also be security issues with sending the wrong content type, such as unexpected injection issues (valid, escaped JSON parsed as HTML.)

Best to fix the problem at the source, and send the right content type.

**Comment by mpchadwick** [comment]
Looks like New Relic put in a fix on their end in v7.6.0.201 of the PHP Agent

https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-760201

I do agree, though, that Magento should be setting the correct Content-Type.

**Comment by hostep** [comment]
@vrann : I believe you can close this, since the issue got fixed in Magento 2.1.12, 2.2.3, 2.3-develop (by https://github.com/magento/magento2/pull/10521) and was indeed also fixed in New Relic's PHP agent itself like mentioned above.
